# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='command.proto',
  package='vss_command',
  serialized_pb=_b('\n\rcommand.proto\x12\x0bvss_command\"@\n\rRobot_Command\x12\n\n\x02id\x18\x01 \x02(\r\x12\x10\n\x08left_vel\x18\x02 \x02(\x02\x12\x11\n\tright_vel\x18\x03 \x02(\x02\"\x8a\x01\n\x0fGlobal_Commands\x12\n\n\x02id\x18\x01 \x01(\r\x12\x16\n\x0eis_team_yellow\x18\x02 \x01(\x08\x12\x32\n\x0erobot_commands\x18\x03 \x03(\x0b\x32\x1a.vss_command.Robot_Command\x12\x11\n\tsituation\x18\x04 \x01(\r\x12\x0c\n\x04name\x18\x05 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ROBOT_COMMAND = _descriptor.Descriptor(
  name='Robot_Command',
  full_name='vss_command.Robot_Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='vss_command.Robot_Command.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='left_vel', full_name='vss_command.Robot_Command.left_vel', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='right_vel', full_name='vss_command.Robot_Command.right_vel', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=94,
)


_GLOBAL_COMMANDS = _descriptor.Descriptor(
  name='Global_Commands',
  full_name='vss_command.Global_Commands',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='vss_command.Global_Commands.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_team_yellow', full_name='vss_command.Global_Commands.is_team_yellow', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='robot_commands', full_name='vss_command.Global_Commands.robot_commands', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='situation', full_name='vss_command.Global_Commands.situation', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='vss_command.Global_Commands.name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=235,
)

_GLOBAL_COMMANDS.fields_by_name['robot_commands'].message_type = _ROBOT_COMMAND
DESCRIPTOR.message_types_by_name['Robot_Command'] = _ROBOT_COMMAND
DESCRIPTOR.message_types_by_name['Global_Commands'] = _GLOBAL_COMMANDS

Robot_Command = _reflection.GeneratedProtocolMessageType('Robot_Command', (_message.Message,), dict(
  DESCRIPTOR = _ROBOT_COMMAND,
  __module__ = 'command_pb2'
  # @@protoc_insertion_point(class_scope:vss_command.Robot_Command)
  ))
_sym_db.RegisterMessage(Robot_Command)

Global_Commands = _reflection.GeneratedProtocolMessageType('Global_Commands', (_message.Message,), dict(
  DESCRIPTOR = _GLOBAL_COMMANDS,
  __module__ = 'command_pb2'
  # @@protoc_insertion_point(class_scope:vss_command.Global_Commands)
  ))
_sym_db.RegisterMessage(Global_Commands)


# @@protoc_insertion_point(module_scope)
