# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_nrf')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_nrf')
    _nrf = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_nrf', [dirname(__file__)])
        except ImportError:
            import _nrf
            return _nrf
        try:
            _mod = imp.load_module('_nrf', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _nrf = swig_import_helper()
    del swig_import_helper
else:
    import _nrf
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class NRF(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, NRF, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, NRF, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _nrf.new_NRF(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _nrf.delete_NRF
    __del__ = lambda self: None

    def setup(self):
        return _nrf.NRF_setup(self)

    def setMessage(self, start, id, motorSpeed1, motorSpeed2, kickRet, batteryRet, stop):
        return _nrf.NRF_setMessage(self, start, id, motorSpeed1, motorSpeed2, kickRet, batteryRet, stop)

    def send(self, *args):
        return _nrf.NRF_send(self, *args)

    def recv(self):
        return _nrf.NRF_recv(self)

    def setRawBuffer(self, b1, b2, b3):
        return _nrf.NRF_setRawBuffer(self, b1, b2, b3)

    def sendRawBuffer(self):
        return _nrf.NRF_sendRawBuffer(self)

    def startSending(self):
        return _nrf.NRF_startSending(self)

    def stopSending(self):
        return _nrf.NRF_stopSending(self)

    def setNet(self, arg2):
        return _nrf.NRF_setNet(self, arg2)
NRF_swigregister = _nrf.NRF_swigregister
NRF_swigregister(NRF)
DEFAULT_DEVICE_NAME_NRF = _nrf.DEFAULT_DEVICE_NAME_NRF
NRF_BUFFER_SIZE = _nrf.NRF_BUFFER_SIZE
_MSG_BEGIN = _nrf._MSG_BEGIN
_MSG_END = _nrf._MSG_END

# This file is compatible with both classic and new-style classes.


