# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: debug.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='debug.proto',
  package='vss_debug',
  serialized_pb=_b('\n\x0b\x64\x65\x62ug.proto\x12\tvss_debug\"5\n\x04Pose\x12\n\n\x02id\x18\x01 \x02(\r\x12\t\n\x01x\x18\x02 \x02(\x02\x12\t\n\x01y\x18\x03 \x02(\x02\x12\x0b\n\x03yaw\x18\x04 \x01(\x02\"2\n\x04Path\x12\n\n\x02id\x18\x01 \x02(\r\x12\x1e\n\x05poses\x18\x02 \x03(\x0b\x32\x0f.vss_debug.Pose\"y\n\x0cGlobal_Debug\x12#\n\nstep_poses\x18\x01 \x03(\x0b\x32\x0f.vss_debug.Pose\x12$\n\x0b\x66inal_poses\x18\x02 \x03(\x0b\x32\x0f.vss_debug.Pose\x12\x1e\n\x05paths\x18\x03 \x03(\x0b\x32\x0f.vss_debug.Path')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_POSE = _descriptor.Descriptor(
  name='Pose',
  full_name='vss_debug.Pose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='vss_debug.Pose.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='vss_debug.Pose.x', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='vss_debug.Pose.y', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='vss_debug.Pose.yaw', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=79,
)


_PATH = _descriptor.Descriptor(
  name='Path',
  full_name='vss_debug.Path',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='vss_debug.Path.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='poses', full_name='vss_debug.Path.poses', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=131,
)


_GLOBAL_DEBUG = _descriptor.Descriptor(
  name='Global_Debug',
  full_name='vss_debug.Global_Debug',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='step_poses', full_name='vss_debug.Global_Debug.step_poses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='final_poses', full_name='vss_debug.Global_Debug.final_poses', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='paths', full_name='vss_debug.Global_Debug.paths', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=254,
)

_PATH.fields_by_name['poses'].message_type = _POSE
_GLOBAL_DEBUG.fields_by_name['step_poses'].message_type = _POSE
_GLOBAL_DEBUG.fields_by_name['final_poses'].message_type = _POSE
_GLOBAL_DEBUG.fields_by_name['paths'].message_type = _PATH
DESCRIPTOR.message_types_by_name['Pose'] = _POSE
DESCRIPTOR.message_types_by_name['Path'] = _PATH
DESCRIPTOR.message_types_by_name['Global_Debug'] = _GLOBAL_DEBUG

Pose = _reflection.GeneratedProtocolMessageType('Pose', (_message.Message,), dict(
  DESCRIPTOR = _POSE,
  __module__ = 'debug_pb2'
  # @@protoc_insertion_point(class_scope:vss_debug.Pose)
  ))
_sym_db.RegisterMessage(Pose)

Path = _reflection.GeneratedProtocolMessageType('Path', (_message.Message,), dict(
  DESCRIPTOR = _PATH,
  __module__ = 'debug_pb2'
  # @@protoc_insertion_point(class_scope:vss_debug.Path)
  ))
_sym_db.RegisterMessage(Path)

Global_Debug = _reflection.GeneratedProtocolMessageType('Global_Debug', (_message.Message,), dict(
  DESCRIPTOR = _GLOBAL_DEBUG,
  __module__ = 'debug_pb2'
  # @@protoc_insertion_point(class_scope:vss_debug.Global_Debug)
  ))
_sym_db.RegisterMessage(Global_Debug)


# @@protoc_insertion_point(module_scope)
