from rsoccer_gym.vss.env_vss.vss_gym import VSSEnv
from rsoccer_gym.vss.env_vss.vss_1x3 import VSS1x3
from rsoccer_gym.vss.env_vss.vss_1x0 import VSS1x0
from rsoccer_gym.vss.env_vss.vss_goleiro import vss_goleiro
from rsoccer_gym.vss.env_vss.vss_tcc_facil import vss_tcc_facil
from rsoccer_gym.vss.env_vss.vss_tcc_medio import vss_tcc_medio
from rsoccer_gym.vss.env_vss.dumb_attacker import dumb_attacker
from rsoccer_gym.vss.env_vss.vss_tcc_progressivo import vss_tcc_progressivo
from rsoccer_gym.vss.env_vss.vss_tcc_progressive_with_goalkeeper import vss_tcc_progressive_with_goalkeeper
from rsoccer_gym.vss.env_vss.vss_progressive_simple_goalkeeper import vss_progressive_simple_goalkeeper
