from rc_gym.ssl.ssl_hw_challenge.static_defenders import SSLHWStaticDefendersEnv
from rc_gym.ssl.ssl_hw_challenge.dribbling import SSLHWDribblingEnv
from rc_gym.ssl.ssl_hw_challenge.contested_possession import SSLContestedPossessionEnv
