# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages_robocup_ssl_robot_status.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages_robocup_ssl_robot_status.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\'messages_robocup_ssl_robot_status.proto\"5\n\rRobots_Status\x12$\n\rrobots_status\x18\x01 \x03(\x0b\x32\r.Robot_Status\"X\n\x0cRobot_Status\x12\x10\n\x08robot_id\x18\x01 \x02(\x05\x12\x10\n\x08infrared\x18\x02 \x02(\x08\x12\x11\n\tflat_kick\x18\x03 \x02(\x08\x12\x11\n\tchip_kick\x18\x04 \x02(\x08'
)




_ROBOTS_STATUS = _descriptor.Descriptor(
  name='Robots_Status',
  full_name='Robots_Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='robots_status', full_name='Robots_Status.robots_status', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=96,
)


_ROBOT_STATUS = _descriptor.Descriptor(
  name='Robot_Status',
  full_name='Robot_Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='robot_id', full_name='Robot_Status.robot_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='infrared', full_name='Robot_Status.infrared', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flat_kick', full_name='Robot_Status.flat_kick', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chip_kick', full_name='Robot_Status.chip_kick', index=3,
      number=4, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=186,
)

_ROBOTS_STATUS.fields_by_name['robots_status'].message_type = _ROBOT_STATUS
DESCRIPTOR.message_types_by_name['Robots_Status'] = _ROBOTS_STATUS
DESCRIPTOR.message_types_by_name['Robot_Status'] = _ROBOT_STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Robots_Status = _reflection.GeneratedProtocolMessageType('Robots_Status', (_message.Message,), {
  'DESCRIPTOR' : _ROBOTS_STATUS,
  '__module__' : 'messages_robocup_ssl_robot_status_pb2'
  # @@protoc_insertion_point(class_scope:Robots_Status)
  })
_sym_db.RegisterMessage(Robots_Status)

Robot_Status = _reflection.GeneratedProtocolMessageType('Robot_Status', (_message.Message,), {
  'DESCRIPTOR' : _ROBOT_STATUS,
  '__module__' : 'messages_robocup_ssl_robot_status_pb2'
  # @@protoc_insertion_point(class_scope:Robot_Status)
  })
_sym_db.RegisterMessage(Robot_Status)


# @@protoc_insertion_point(module_scope)
